- name: config
  hosts: all
  tasks:
    - name: upgrade system
      become: yes
      pacman:
        update_cache: yes
        upgrade: yes

    - name: install packages
      become: yes
      pacman:
        name:
          - keepassxc
          - neovim
          - python3
          - python-pynvim
          - redshift
          - fish
          - bat
          - starship
          - exa
          - fd
          - ripgrep
          - powerline
          - powerline-fonts
          - firefox-developer-edition
          - xcape
          - caprine
          - shutter
          - xfce4-clipman-plugin
          - fzf
          - obs-studio
          - zathura
          - zathura-pdf-mupdf
          - stow
          - zsh
          - dust
          - nodejs
          - npm
        state: latest

          # fixme!
          #     - name: create cache dir for yay
          #       shell: mkdir -p /var/cache/yay
          # 
          #     - name: install packages with yay
          #       become: yes
          #       pacman:
          #         name:
          #           - onedriver
          #           - bluemail
          #           - whatsapp-for-linux
          #           - signal-desktop-beta
          #           - netflix-git
          #           - nordvpn-bin
          #           - notion-app
          #           - ripgrep-all
          #         state: latest
          #         executable: yay
          #         extra_args: --builddir /var/cache/yay
          #         force: yes
          # 
          #     - name: enable nordvpn user
          #       become: yes
          #       shell: usermod -aG nordvpn $USER
          # 
          #     - name: enable + start nordvpn service
          #       become: yes
          #       service:
          #         name: nordvpnd.service
          #         enabled: yes
          #         state: started

