- name: config
  hosts: all
  tasks:
    - name: upgrade system
      become: yes
      community.general.pacman:
        update_cache: yes
        upgrade: yes

    - name: install packages
      become: yes
      community.general.pacman:
        name:
          - keepassxc
          - neovim
          - python-pynvim
          - redshift
          - fish
          - bat
          - starship
          - exa
          - fd
          - ripgrep
          - powerline
          - powerline-fonts
          - firefox-developer-edition
          - xcape
          - caprine
          - shutter
          - xfce4-clipman-plugin
          - fzf
          - obs-studio
          - zathura
          - zathura-pdf-mupdf
          - stow
          - zsh
          - dust
        state: latest

          # fixme!
          #     - name: create cache dir for yay
          #       become: yes
          #       shell: mkdir -p /var/cache/yay
          # 
          #     - name: install packages with yay
          #       become: yes
          #       pacman:
          #         name:
          #           - onedriver
          #           - bluemail
          #           - whatsapp-for-linux
          #           - signal-desktop-beta
          #           - netflix-git
          #           - nordvpn-bin
          #           - notion-app
          #           - ripgrep-all
          #         state: latest
          #         executable: yay
          #         extra_args: --builddir /var/cache/yay
          #         force: yes
          # 
          #     - name: enable nordvpn user
          #       become: yes
          #       shell: usermod -aG nordvpn $USER
          # 
          #     - name: enable + start nordvpn service
          #       become: yes
          #       service:
          #         name: nordvpnd.service
          #         enabled: yes
          #         state: started

    - name: set fish as default shell
      user: 
        name: "{{ exec_username }}"
        shell: /usr/bin/fish

    - name: install Plug for nvim
      shell:  |
        sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \
             https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'

    - name: install plugins for nvim
      shell: nvim +PlugInstall +qa

    - name: install npm packages
      shell: | 
        npm install --global yarn
        npm install coc-ccls

