- block:
  - name: Install bumblebee
    become_user: "{{ ansible_user }}"
    kewlfft.aur.aur:
      use: paru
      name:
        - bumblebee
        - mesa
        - lib32-virtualgl
        - nvidia-390xx-dkms
        - lib32-nvidia-390xx-utils

  - name: Add "{{ ansible_user }}" to bumblebee group
    user:
      name: "{{ ansible_user }}"
      groups: bumblebee
      append: yes

  - name: Enable bumblebee service
    service:
      name: bumblebeed
      enabled: yes

  - name: Reboot
    become: yes
    reboot:

  become: yes
