- block:
  - name: run stow for xmonad on .dotfiles
    shell: |
      cd ~/.dotfiles
      stow --adopt xmonad

  - name: recompile and restart xmonad
    shell: |
      xmonad --recompile 
      xmonad --restart
      exit 0

  - name: add 'screen_setup.sh' to 'Xsetup'
    become: yes
    lineinfile:
      path: /usr/share/sddm/scripts/Xsetup
      state: present
      line: "/home/{{ ansible_user }}/.xmonad/scripts/screen_setup.sh"
